# Generated by Django 5.1.4 on 2025-01-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_user', '0002_user_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='user',
        ),
    ]
