# Generated by Django 5.1.4 on 2025-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_user', '0003_remove_user_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='user_account',
            name='location',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='user_account',
            name='phone_number',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
