# Generated by Django 5.1.4 on 2025-01-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_user', '0005_purchase_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase_record',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Purchase Record', 'verbose_name_plural': 'Purchase Records'},
        ),
    ]
