# Generated by Django 5.1.4 on 2025-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_user', '0007_users_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_record',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
