# Generated by Django 5.1.4 on 2025-01-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_user', '0008_purchase_record_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
    ]
