# Generated by Django 5.1.4 on 2025-01-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0017_alter_adminlogs_options_alter_coffee_options'),
        ('z_user', '0009_alter_user_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_feedback',
            name='coffee',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='z_admin.coffee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users_feedback',
            name='comment',
            field=models.TextField(),
        ),
    ]
