# Generated by Django 5.1.4 on 2025-01-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0002_admin_account_delete_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Account',
        ),
    ]
