# Generated by Django 5.1.4 on 2025-01-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0007_order'),
        ('z_user', '0006_alter_purchase_record_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='z_user.user_account'),
        ),
    ]
