# Generated by Django 5.1.4 on 2025-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=10),
        ),
    ]
