# Generated by Django 5.1.4 on 2025-01-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0010_remove_order_status_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_admin.admin_account')),
            ],
        ),
    ]
