# Generated by Django 5.1.4 on 2025-01-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0011_adminlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogs',
            name='action',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
