# Generated by Django 5.1.4 on 2025-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0013_alter_order_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
