# Generated by Django 5.1.4 on 2025-01-10 14:06

import z_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0014_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='coffee_img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=z_admin.models.img_path),
        ),
    ]
