# Generated by Django 5.1.4 on 2025-01-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0015_coffee_coffee_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='coffee_img',
            new_name='image',
        ),
    ]
