# Generated by Django 5.1.4 on 2025-01-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_admin', '0016_rename_coffee_img_coffee_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogs',
            options={'ordering': ['-log_time'], 'verbose_name': 'AdminLogs', 'verbose_name_plural': 'AdminLogs'},
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coffee', 'verbose_name_plural': 'Coffees'},
        ),
    ]
